### ISSUE TITLE
Hello, what I understand is that the final result of the Mapclosure algorithm is the possible loop graph index, and then I can get a pair of optimal loop indexes based on the number of interior points. I can think that these two local maps contain the same robot return. The pose point of the position, but how can I determine which point is the same position? The mapclosure algorithm is a loop closure between local maps, and the scancontext is a loop closure detection between individual frames. Later, I need to compare these two algorithms and compare mapclousre How does the algorithm loopback work? One is a local graph and the other is a single frame. How do you compare them?

### ISSUE THREAD

**Issue by LL884800** [PRBonn/MapClosures#33]
Hello, I want to know how I can be sure that the loop diagram is obtained by using this algorithm. Then how can I be sure that the robot has returned to its original position? If I only get the loop diagram, how can I compare it with the scan context? After all, scan context It is possible to obtain the specific pose of the robot when it returns to its original position.

**Comment by saurabh1002** [comment]
Hello @LL884800, thanks for showing interest in our work.
To begin with, I am not exactly sure what you mean by a "loop diagram". It would be great if you can elaborate a bit further!

Secondly, a one-to-one comparison with ScanContext is not possible since the two approaches are different in the way they process data. ScanContext works on individual scans, whereas we work on local maps generated from registered scans within a certain distance. So each local map contains multiple individual scans.

As a result the start position of the robot and certain number of subsequent scans are contained within the first local map. To figure out if you are revisiting the start location, you can check for the local map index of the loop closures obtained, whether the reference index is `0` or not.

The following image shows how we save the closure information in out `pipeline.py`:
![image](https://github.com/user-attachments/assets/f1b1769b-78c3-4d6f-9d64-d9ed76f4468c)

The relative pose we provide is between the first scans in the source and the target local maps respectively. This is because each local map is in the local reference frame of the first scan it contains.

**Comment by saurabh1002** [comment]
You can check out #24 to see how we integrate the detected closures between local maps to perform a pose-graph optimization. This PR will be soon merged with the main branch.

**Comment by saurabh1002** [comment]
Hey, it would be great if you can add comments to this issue rather than editing the title of the issue in reply.

**Comment by saurabh1002** [comment]
You can find the way we compute scan-level closure indices from the map-level closures in `tools/evaluation.py` and is also mentioned in the paper. We use the provided script to compute scan-level closures to compare with scan context, through the Precion Recall and F1 score.

**Comment by LL884800** [comment]
你好，我的理解是Mapclosure算法最终得到的结果是可能的回环图索引，然后根据内点个数可以得到一对最优回环索引，我可以认为这两个局部地图包含了机器人回环相同位置的pose点，但是我怎么才能确定哪个点是相同位置呢？这里我想知道的是我怎么确定哪个点被认为回到了相同的位置，mapclosure算法是局部地图之间的回环，而scancontext是单帧之间的回环检测，后面我需要对比这两个算法，比较mapclousre算法回环是如何进行的？一个是局部图，一个是单帧，请问怎么比较呢？

**Comment by LL884800** [comment]
Hello, my understanding is that the final result of the map closure algorithm is a possible loop graph index, and then an optimal loop index can be obtained based on the number of interior points. I can think that these two local maps contain the posture of the robot looping at the same position. points, but how can I determine which point is the same location? What I want to know here is how I determine which point is considered to have returned to the same position. The map closure algorithm is the loop closure between local maps, while the scanning context is the loop closure detection between single frames. I need to compare these two algorithms later. Compare how mapclousre algorithm loopback is performed? One is a partial image and the other is a single frame. How do they compare?
